#try:
#    # シンタックスエラーも補足されるのかなと思ったけどさすがにそんなことはなかった（実行すらできない）
#    while True print("aaaaaa")
#except:
#    print("Unexpected error:")
